version: '3'

services:
  app:
    build: .
    environment:
      - APP_NAME=Sample PHP Application
      - APP_URL=http://apperdevops.com
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USERNAME=sample
      - DB_PASSWORD=sample
      - DB_NAME=sample
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
